"""The within-run pairing artifacts regenerate byte-exactly from their rows.

``evals/beam_within_run_pairs.py`` produces the paired column the
comparator-arms table in ``evals/README.md`` publishes (arm minus ``rag``,
95% CI, sign-flip permutation p, served characters and tokens). Each
artifact is a claim about a committed ``.jsonl``; these tests re-derive
them from those rows with the same seed so the two cannot drift apart,
and pin the arm shapes the docs describe.

Two harnesses, one tool since 2026-09-04. BEAM keys its verdict
``{arm}_score`` and its ability ``type``; LongMemEval keys those
``{arm}_correct`` (boolean) and ``question_type``, and carries a derived
``cascade`` arm. The LongMemEval artifact below was first written by an
inline script with no committed producer — which is precisely the failure
the "every bench writes a file" rule exists to stop — so it is
regenerated by the tool and pinned here like the BEAM one.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "evals"))

from beam_within_run_pairs import CONTROL, pair_run  # noqa: E402

RESULTS = REPO / "evals" / "results"
ROWS = RESULTS / "beam-100K-qwen-27b-chip12-b16.jsonl"
ARTIFACT = RESULTS / "beam-100K-qwen-27b-chip12-b16.arms-vs-rag.json"
ARMS = ["refind", "hybrid", "cortex", "nomem"]

# The 500-question LongMemEval six-type sweep with the rag-lite arms.
LME_ROWS = RESULTS / "longmemeval-all-oracle-qwen-27b-raglite-all-fresh.jsonl"
LME_ARTIFACT = RESULTS / (
    "longmemeval-all-oracle-qwen-27b-raglite-all-fresh.arms-vs-rag.json")
LME_ARMS = ["cortex", "hybrid", "rag1", "rag2", "ragb400", "cascade"]


def _rows() -> list[dict]:
    return [json.loads(line) for line in ROWS.read_text(encoding="utf-8")
            .splitlines() if line.strip()]


@pytest.mark.skipif(not ROWS.exists(), reason="chip12-b16 rows not checked out")
def test_artifact_regenerates_byte_exactly():
    committed = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    regenerated = pair_run(_rows(), ARMS, perms=committed["perms"],
                           seed=committed["seed"])
    regenerated["source"] = ROWS.name
    assert (json.dumps(regenerated, indent=2, sort_keys=True) + "\n"
            == ARTIFACT.read_text(encoding="utf-8"))


def test_artifact_shape_matches_docs():
    d = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    assert d["control"] == CONTROL == "rag"
    assert d["n_rows"] == 400
    assert set(d["arms"]) == set(ARMS)
    for arm in ARMS:
        a = d["arms"][arm]
        assert a["n"] == 400
        assert a["wins"] + a["losses"] + a["ties"] == 400
        assert set(a["types"]) == set(d["control_types"])
    # The no-memory floor is served nothing, by construction.
    assert d["arms"]["nomem"]["context_chars_mean"] == 0
    assert d["arms"]["nomem"]["types"]["abstention"] == 1.0
    # Cost beside accuracy in the same table (2026-09-04): the fact spine
    # is served an order of magnitude fewer tokens than the rag control it
    # is scored against, which is the trade-off the arm table exists to
    # show. The estimator floors at 1, so the served-nothing arm reads 1.
    assert d["control_context_tokens_mean"] == 5539
    assert d["arms"]["cortex"]["context_tokens_mean"] == 551
    assert d["arms"]["nomem"]["context_tokens_mean"] == 1
    for arm in ARMS:
        a = d["arms"][arm]
        assert a["context_tokens_mean"] == max(1, a["context_chars_mean"] // 4)


def test_pair_run_on_a_tiny_run_is_exact():
    rows = [
        {"type": "t", "rag_score": 1.0, "x_score": 0.0,
         "contexts": {"rag": "abcd", "x": ""}},
        {"type": "t", "rag_score": 0.5, "x_score": 0.5,
         "contexts": {"rag": "ab", "x": "abcdef"}},
        {"type": "u", "rag_score": 0.0, "x_score": 1.0,
         "contexts": {"rag": "", "x": "abc"}},
    ]
    d = pair_run(rows, ["x"], perms=200, seed=0)
    x = d["arms"]["x"]
    assert x["n"] == 3
    assert x["delta_vs_control"] == 0.0
    assert (x["wins"], x["losses"], x["ties"]) == (1, 1, 1)
    assert x["full_marks_rows"] == 1
    assert x["types"] == {"t": 0.25, "u": 1.0}
    assert x["context_chars_mean"] == 3
    assert d["control_context_chars_mean"] == 2
    assert x["perm_p"] == 1.0


# ── the LongMemEval side of the same tool ─────────────────────────────────
def _lme_rows() -> list[dict]:
    return [json.loads(line) for line in
            LME_ROWS.read_text(encoding="utf-8").splitlines() if line.strip()]


@pytest.mark.skipif(not LME_ROWS.exists(),
                    reason="raglite-all-fresh rows not checked out")
def test_lme_artifact_regenerates_byte_exactly():
    committed = json.loads(LME_ARTIFACT.read_text(encoding="utf-8"))
    regenerated = pair_run(_lme_rows(), LME_ARMS, perms=committed["perms"],
                           seed=committed["seed"], score_key="correct",
                           type_key="question_type",
                           pairs=(("cortex", "rag1"),))
    regenerated["source"] = LME_ROWS.name
    regenerated["note"] = committed["note"]
    assert (json.dumps(regenerated, indent=2, sort_keys=True) + "\n"
            == LME_ARTIFACT.read_text(encoding="utf-8"))


def test_lme_artifact_shape_matches_docs():
    d = json.loads(LME_ARTIFACT.read_text(encoding="utf-8"))
    assert d["control"] == CONTROL == "rag"
    assert d["n_rows"] == 500
    assert set(d["arms"]) == set(LME_ARMS)
    for arm in LME_ARMS:
        assert d["arms"][arm]["n"] == 500
    # The token-matched reading the runbook publishes: at ~200 served
    # tokens the one-turn RAG arm scores within noise of the fact spine at
    # ~97, and the pairing between them is flat.
    assert d["arms"]["cortex"]["context_tokens_mean"] == 97
    assert d["arms"]["rag1"]["context_tokens_mean"] == 206
    assert d["pairs"]["cortex-rag1"]["delta"] == -0.006
    assert d["pairs"]["cortex-rag1"]["perm_p"] > 0.05


def test_boolean_verdicts_read_as_one_and_zero():
    """LongMemEval rows carry booleans where BEAM carries rubric floats."""
    rows = [
        {"question_type": "t", "rag_correct": True, "x_correct": False},
        {"question_type": "t", "rag_correct": False, "x_correct": True},
    ]
    d = pair_run(rows, ["x"], perms=200, seed=0, score_key="correct",
                 type_key="question_type")
    assert d["control_mean"] == 0.5
    assert d["arms"]["x"]["mean"] == 0.5
    assert (d["arms"]["x"]["wins"], d["arms"]["x"]["losses"]) == (1, 1)


def test_pairs_are_absent_unless_asked_for():
    """A BEAM artifact written before --pairs must regenerate unchanged."""
    rows = [{"type": "t", "rag_score": 1.0, "x_score": 0.0,
             "contexts": {"rag": "abcd", "x": ""}}]
    assert "pairs" not in pair_run(rows, ["x"], perms=10, seed=0)
    assert "pairs" in pair_run(rows, ["x"], perms=10, seed=0,
                               pairs=(("x", "rag"),))


def test_cascade_on_rows_that_cannot_carry_one_says_so():
    """BEAM scores a rubric float, so its rows carry no boolean verdict and
    no cascade. A bare KeyError three frames down would read as a bug in
    the tool rather than a wrong --arms list."""
    rows = [{"type": "t", "rag_score": 1.0}]
    with pytest.raises(SystemExit, match="derived cascade arm needs"):
        pair_run(rows, ["cascade"], perms=10, seed=0)

def test_perm_p_is_small_for_a_one_sided_run():
    # Eight rows all favouring the arm by a full point: the permutation
    # loop runs (mean != 0), and only the all-same-sign draws reach the
    # observed statistic, so p sits near 2/2^8 plus the +1 smoothing.
    rows = [{"type": "t", "rag_score": 0.0, "x_score": 1.0}
            for _ in range(8)]
    x = pair_run(rows, ["x"], perms=2000, seed=0)["arms"]["x"]
    assert x["delta_vs_control"] == 1.0
    assert 0.0 < x["perm_p"] < 0.05
    assert x["context_chars_mean"] is None
